version: '3.1'
services:
#  db:
#    image: mysql
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#    - "3306:3306"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    volumes:
    - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
#    - '--config.file=/etc/prometheus/prometheus.yml'
#    - devdojo_data:/var/lib/mysql
    ports:
     - "9090:9090"
volumes:
  devdojo_data:
